package site.hsu.hub.recruitment.adapter.in.web;
import com.fasterxml.jackson.databind.JsonNode;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.web.bind.annotation.*;import site.hsu.hub.common.api.*;import site.hsu.hub.recruitment.application.*;import java.time.Instant;import java.util.*;import static site.hsu.hub.recruitment.domain.RecruitmentCommands.*;
@RestController@RequestMapping("/api/v1/operator/clubs/{clubId}/recruitments")public class OperatorRecruitmentController implements OperatorRecruitmentControllerDocs{
 private final RecruitmentService service;public OperatorRecruitmentController(RecruitmentService service){this.service=service;}
 @Override@GetMapping public ApiResponse<List<RecruitmentService.RecruitmentView>>list(@PathVariable Long clubId,HttpServletRequest req){return Responses.ok(service.operatorList(clubId),req);}
 @Override@PostMapping public ApiResponse<RecruitmentService.RecruitmentView>publish(@PathVariable Long clubId,@Valid@RequestBody PublishRequest body,HttpServletRequest req){return Responses.ok(service.publish(clubId,body.command()),req);}
 public record PublishRequest(@NotBlank@Size(max=160)String title,@Min(1)int quota,@NotNull Instant opensAt,@NotNull Instant closesAt,JsonNode contentBlocks,@NotNull List<@Valid StageRequest>stages,@NotNull@Valid FormRequest form){PublishCommand command(){return new PublishCommand(title,quota,opensAt,closesAt,contentBlocks,stages.stream().map(StageRequest::command).toList(),form.command());}}
 public record StageRequest(@NotBlank String type,@NotBlank@Size(max=100)String label,Instant startsAt,Instant endsAt,boolean enabled){StageCommand command(){return new StageCommand(type,label,startsAt,endsAt,enabled);}}
 public record FormRequest(@NotEmpty List<@Valid StepRequest>steps){FormCommand command(){return new FormCommand(steps.stream().map(StepRequest::command).toList());}}
 public record StepRequest(@NotBlank@Size(max=100)String title,@NotEmpty List<@Valid QuestionRequest>questions){StepCommand command(){return new StepCommand(title,questions.stream().map(QuestionRequest::command).toList());}}
 public record QuestionRequest(@NotBlank String type,@NotBlank@Size(max=300)String label,boolean required,@Size(max=500)String helpText,@Size(max=300)String placeholder,@Min(1)@Max(10000)Integer maxLength,List<@Size(max=300)String>options){QuestionCommand command(){return new QuestionCommand(type,label,required,helpText,placeholder,maxLength,options==null?List.of():options);}}
}
