package site.hsu.hub;
import java.util.UUID;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.MockMvc;import static org.hamcrest.Matchers.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc class ApiContractTest{@Autowired MockMvc mvc;
 @Test void unauthorizedJsonUsesEnvelopeAndRequestId()throws Exception{mvc.perform(get("/api/v1/clubs")).andExpect(status().isUnauthorized()).andExpect(header().exists("X-Request-ID")).andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.code").value("UNAUTHORIZED")).andExpect(jsonPath("$.requestId",not(blankOrNullString())));}
 @Test void csrfIsRequiredForStateChangingRequest()throws Exception{mvc.perform(post("/api/v1/auth/signup").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"student@hansung.ac.kr\",\"password\":\"password1234\"}")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("FORBIDDEN"));}
 @Test void bypassedFrontendDomainCheckReturns422()throws Exception{mvc.perform(post("/api/v1/auth/signup").with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"student@example.com\",\"password\":\"password1234\"}")).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.code").value("EMAIL_DOMAIN_NOT_ALLOWED"));}
 @Test void duplicateSignupDoesNotRevealWhetherEmailExists()throws Exception{String email=UUID.randomUUID()+"@hansung.ac.kr";String body="{\"email\":\""+email+"\",\"password\":\"password1234\"}";mvc.perform(post("/api/v1/auth/signup").with(csrf()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());mvc.perform(post("/api/v1/auth/signup").with(csrf()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true));}
 @Test void openApiCarriesKoreanControllerDocs()throws Exception{mvc.perform(get("/v3/api-docs")).andExpect(status().isOk()).andExpect(content().string(containsString("한성대학교 이메일"))).andExpect(content().string(containsString("모집 게시")));}
 @Test void unknownFrontendCannotSelectAnOAuthCallbackOrigin()throws Exception{mvc.perform(get("/api/v1/auth/kakao/start").header("X-HSU-Frontend","evil")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("BAD_REQUEST"));}
 @Test void removedApiRouteReturnsWrapped404()throws Exception{mvc.perform(get("/api/v1/interviews").with(user("verified"))).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("NOT_FOUND"));}
}
