package site.hsu.hub;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.transaction.annotation.Transactional;import site.hsu.hub.application.application.ApplicationService;import site.hsu.hub.club.adapter.out.persistence.*;import site.hsu.hub.club.application.ClubService;import site.hsu.hub.club.domain.ClubRole;import site.hsu.hub.common.exception.ApiException;import site.hsu.hub.identity.adapter.out.persistence.*;import site.hsu.hub.identity.api.SessionUser;import site.hsu.hub.identity.domain.ServiceRole;import site.hsu.hub.recruitment.application.RecruitmentService;import site.hsu.hub.recruitment.adapter.out.persistence.RecruitmentRepository;import site.hsu.hub.recruitment.domain.RecruitmentCommands.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;
@SpringBootTest@Transactional class BackendFlowIntegrationTest{
 @Autowired UserRepository users;@Autowired ClubRepository clubs;@Autowired ClubUserRepository mappings;@Autowired ClubService clubService;@Autowired RecruitmentService recruitments;@Autowired RecruitmentRepository recruitmentRepository;@Autowired ApplicationService applications;
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 private Setup setup(){var user=new UserEntity(UUID.randomUUID()+"@hansung.ac.kr","unused");user.verify(Instant.now());users.save(user);var club=clubs.save(new ClubEntity("테스트 동아리","IT/개발"));mappings.save(new ClubUserEntity(user.id(),club.id(),ClubRole.OPERATOR));SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(new SessionUser(user.id(),user.email(),ServiceRole.USER),null,List.of()));return new Setup(user.id(),club.id());}
 @Test void crossClubAccessIsConcealed(){setup();var other=clubs.save(new ClubEntity("다른 동아리","체육"));assertThatThrownBy(()->clubService.operatorGet(other.id())).isInstanceOf(ApiException.class).extracting(e->((ApiException)e).code().name()).isEqualTo("NOT_FOUND");}
 @Test void overlappingPublicationIsRejectedAndSubmissionReplaysByIdempotencyKey(){var s=setup();Instant now=Instant.now();var question=new QuestionCommand("SHORT_TEXT","이름",true,null,null,100,List.of());var command=new PublishCommand("2026 하반기 모집",5,now.minusSeconds(60),now.plusSeconds(3600),null,List.of(),new FormCommand(List.of(new StepCommand("기본 정보",List.of(question)))));var published=recruitments.publish(s.clubId(),command);assertThatThrownBy(()->recruitments.publish(s.clubId(),command)).isInstanceOf(ApiException.class);Long questionId=recruitments.form(published.id()).questions().getFirst().id();var first=applications.submit(published.id(),"same-key",Map.of(questionId.toString(),"홍길동"),null,null,null);closeRecruitment(published.id());var replay=applications.submit(published.id(),"same-key",Map.of(questionId.toString(),"홍길동"),null,null,null);assertThat(replay.publicId()).isEqualTo(first.publicId());assertThat(replay.replayed()).isTrue();}
 record Setup(Long userId,Long clubId){}
 private void closeRecruitment(Long id){try{var entity=recruitmentRepository.findById(id).orElseThrow();var field=entity.getClass().getDeclaredField("closesAt");field.setAccessible(true);field.set(entity,Instant.now().minusSeconds(1));recruitmentRepository.flush();}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
}
