import React, { useEffect, useState } from 'react';
import { Camera, Save } from 'lucide-react';
import { useOperator } from './OperatorContext';
import { api, messageOf } from './api';
import { ErrorNotice, PageHeader } from './Shell';

export default function ClubProfile() {
  const { clubId, selectedClub } = useOperator(); const [form, setForm] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [cover, setCover] = useState(null);
  useEffect(() => { if (!clubId) return; setForm(null); setError(''); api.get(`/operator/clubs/${clubId}`).then(setForm).catch((reason) => setError(messageOf(reason))); }, [clubId]);
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { await api.patch(`/operator/clubs/${clubId}`, { shortIntroduction: form.shortIntroduction ?? '', detailedIntroduction: form.detailedIntroduction ?? '', activityPeriod: form.activityPeriod ?? '', activityPlace: form.activityPlace ?? '' }); if (cover) { const data = new FormData(); data.append('file', cover); await api.put(`/operator/clubs/${clubId}/cover`, data); setCover(null); } setNotice('동아리 프로필을 저장했습니다. 지원자 화면에도 바로 반영됩니다.'); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } }
  return <main className="prod-page"><PageHeader eyebrow="CLUB PROFILE" title="동아리 프로필" description="모집 여부와 관계없이 지원자에게 보여지는 기본 정보를 관리합니다." />{!form ? <div className="prod-loading inline"><span /><p>{error || '프로필을 불러오는 중입니다'}</p></div> : <form className="profile-layout" onSubmit={save}><section className="prod-panel profile-form"><div className="section-title"><span>01</span><div><h2>소개 정보</h2><p>동아리의 성격이 한눈에 드러나는 문장을 작성해 주세요.</p></div></div><label>짧은 소개 <small>{(form.shortIntroduction ?? '').length}/100</small><input maxLength="100" value={form.shortIntroduction ?? ''} onChange={(e) => setForm({ ...form, shortIntroduction: e.target.value })} placeholder="예: 아이디어를 현실로 만드는 IT 창업 동아리" /></label><label>상세 소개 <small>{(form.detailedIntroduction ?? '').length}/2000</small><textarea rows="9" maxLength="2000" value={form.detailedIntroduction ?? ''} onChange={(e) => setForm({ ...form, detailedIntroduction: e.target.value })} placeholder="주요 활동과 동아리 문화를 자세히 소개해 주세요." /></label><div className="two-fields"><label>활동 기간<input value={form.activityPeriod ?? ''} onChange={(e) => setForm({ ...form, activityPeriod: e.target.value })} placeholder="매주 목요일 18:00" /></label><label>활동 장소<input value={form.activityPlace ?? ''} onChange={(e) => setForm({ ...form, activityPlace: e.target.value })} placeholder="상상관 12층" /></label></div></section><aside className="prod-panel cover-panel"><div className="section-title"><span>02</span><div><h2>대표 커버</h2><p>목록 썸네일과 상세 히어로에 사용됩니다.</p></div></div><div className="cover-preview" style={{ backgroundImage: `linear-gradient(180deg,transparent,rgba(4,15,31,.78)),url(${cover ? URL.createObjectURL(cover) : `/api/v1/clubs/${clubId}/cover`})` }}><small>{form.category ?? selectedClub?.category}</small><strong>{form.name ?? selectedClub?.name}</strong></div><label className="upload-button"><Camera size={17} />{cover ? cover.name : 'JPG, PNG, WebP 선택'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setCover(e.target.files?.[0] ?? null)} /></label><p>최대 5MB · 가로형 이미지 권장</p></aside><div className="save-bar"><div><ErrorNotice>{error}</ErrorNotice>{notice && <p className="prod-success" role="status">{notice}</p>}</div><button className="prod-button primary" disabled={busy}><Save size={17} />{busy ? '저장 중…' : '변경사항 저장'}</button></div></form>}</main>;
}
