package site.hsu.hub.file.application;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.transaction.support.*; import site.hsu.hub.common.exception.*; import site.hsu.hub.file.adapter.out.persistence.*; import site.hsu.hub.file.api.*; import site.hsu.hub.file.application.port.ObjectStorage; import site.hsu.hub.file.domain.*; import java.util.UUID; import java.security.*; import java.util.HexFormat;
@Service public class FileService implements FileStorageService {
 private final FileAssetRepository files; private final FileCleanupTaskRepository cleanup; private final ObjectStorage objects; public FileService(FileAssetRepository files,FileCleanupTaskRepository cleanup,ObjectStorage objects){this.files=files;this.cleanup=cleanup;this.objects=objects;}
 @Transactional public StoredFile storeResume(String name,String type,byte[] bytes){FileValidation.validateResume(name,type,bytes);return store(name,"application/pdf",bytes,FilePurpose.RESUME);}
 @Transactional public StoredFile storeCover(String name,String type,byte[] bytes){FileValidation.validateCover(name,type,bytes);return store(name,type.toLowerCase(),bytes,FilePurpose.CLUB_COVER);}
 @Transactional public StoredFile storeIntroductionImage(String name,String type,byte[] bytes){FileValidation.validateIntroductionImage(name,type,bytes);return store(name,type.toLowerCase(),bytes,FilePurpose.CLUB_INTRODUCTION);}
 private StoredFile store(String name,String type,byte[] bytes,FilePurpose purpose){String key=UUID.randomUUID().toString();try{objects.put(key,type,bytes);if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){public void afterCompletion(int status){if(status!=STATUS_COMMITTED)safeDelete(key);}});var entity=files.save(new FileAssetEntity(key,FileValidation.sanitizeFilename(name),type,bytes.length,sha256(bytes),purpose));return new StoredFile(entity.id(),entity.filename(),entity.mediaType(),entity.size(),entity.sha256(),null);}catch(ApiException e){safeDelete(key);throw e;}catch(RuntimeException e){safeDelete(key);throw new ApiException(ErrorCode.STORAGE_UNAVAILABLE);}}
 @Transactional(readOnly=true) public StoredFile read(Long id){var f=files.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND));try{return new StoredFile(f.id(),f.filename(),f.mediaType(),f.size(),f.sha256(),objects.get(f.objectKey()));}catch(RuntimeException e){throw new ApiException(ErrorCode.STORAGE_UNAVAILABLE);}}
 @Transactional public void delete(Long id){files.findById(id).ifPresent(f->{try{objects.delete(f.objectKey());files.delete(f);}catch(RuntimeException e){cleanup.save(new FileCleanupTaskEntity(f.id(),f.objectKey()));}});}
 private void safeDelete(String key){try{objects.delete(key);}catch(RuntimeException ignored){}}
 private static String sha256(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
